### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by patkan** [fau-fablab/acrylschild-designer#4]
Ich fände cool, wenn das Skript in einem Dockercontainer landen würde, der einen Server hochzieht mit dem Service.
Dann könnte man das final auf brain laufen lassen. :-)

**Comment by sedrubal** [comment]
so sollte es erstmal funktionieren. Allerdings will man für production dann wahrscheinlich nicht ubuntu:14.04 von dockerhub holen, sondern ein eigenes image für apache und php5 haben. Außerdem muss man noch schauen, ob man überhaupt apache haben will und ob man nicht php-fpm verwenden will.
